.\" SPDX-License-Identifier: GPL-2.0-only
.\" SPDX-FileCopyrightText: 2018-2026 KUNBUS GmbH
.TH KB_GET_DEVICE_INFO_LIST 2 2026-08-14 "Linux"

.SH NAME
KB_GET_DEVICE_INFO_LIST \- List devices connected to the piControl driver

.SH SYNOPSIS
.nf
.B "#include <piControl.h>"
.B "#include <sys/ioctl.h>"
.sp
.BI "int ioctl(int " fd ", KB_GET_DEVICE_INFO_LIST, SDeviceInfo *" devices ");"
.sp
.B "#include <piControl.h>"
.sp
.B "typedef struct SDeviceInfoStr SDeviceInfo;"
.fi

.SH DESCRIPTION
Get a list of currently configured or connected expansion modules.
The
.I devices
argument should be a preallocated array of
.I REV_PI_DEV_CNT_MAX
.BR SDeviceInfo (2type)
elements that is filled by the piControl driver.

.SH RETURN VALUE
.B KB_GET_DEVICE_INFO_LIST
returns the number of devices that were filled in the
.I devices
array.

On error, \-1 is returned and
.I errno
is set to indicate the error.

.SH ERRORS
Error codes set in
.I errno
can be, among others, one of the following:
.TP
.B ENOMEM
Failure when allocating.
.TP
.B EFAULT
Failure on copying values to/from caller.

.SH SEE ALSO
.BR ioctl (2),
.BR KB_GET_DEVICE_INFO (2),
.BR SDeviceInfo (2type)
