.\" SPDX-License-Identifier: GPL-2.0-only
.\" SPDX-FileCopyrightText: 2018-2026 KUNBUS GmbH
.TH KB_SET_OUTPUT_WATCHDOG 2 2026-08-14 "Linux"

.SH NAME
KB_SET_OUTPUT_WATCHDOG \- Set watchdog timer for all outputs in the piControl
driver

.SH SYNOPSIS
.nf
.B "#include <piControl.h>"
.B "#include <sys/ioctl.h>"
.sp
.BI "int ioctl(int " fd ", KB_SET_OUTPUT_WATCHDOG, unsigned int *" timeout ");"
.fi

.SH DESCRIPTION
Set the watchdog timeout for zeroing all outputs when no write happened after
the given
.IR timeout .

The
.I timeout
parameter is the watchdog timeout in milliseconds. When this is set to
something other than
.BR 0 ,
all outputs will be zeroed if the file handle isn't written to within this
timeout.

The watchdog can be disabled if the
.I timeout
parameter is set to
.BR 0 ,
or when the file handle to
.BR piControl (4)
is closed.

.SH RETURN VALUE
On success, 0 is returned.

On error, \-1 is returned and
.I errno
is set to indicate the error.

.SH ERRORS
Error codes set in
.I errno
can be, among others, one of the following:
.TP
.B EFAULT
Failure on copying the
.I timeout
parameter from the caller.

.SH SEE ALSO
.BR ioctl (2),
.BR piControl (4)
