.\" SPDX-License-Identifier: GPL-2.0-only
.\" SPDX-FileCopyrightText: 2018-2026 KUNBUS GmbH
.TH KB_SET_VALUE 2 2026-08-14 "Linux"

.SH NAME
KB_SET_VALUE \- Set the value of a variable from the piControl driver

.SH SYNOPSIS
.nf
.B "#include <piControl.h>"
.B "#include <sys/ioctl.h>"
.sp
.BI "int ioctl(int " fd ", KB_SET_VALUE, SPIValue *" value ");"
.sp
.B "#include <piControl.h>"
.sp
.B "typedef struct SPIValueStr SPIValue;"
.fi

.SH DESCRIPTION
Set a value in the process image, given the address and value, and optionally
the bit position if only a single bit should be written.

The
.I i16uAddress
and
.I i8uValue
fields of the struct
.BR SPIValue (2type)
must be set to the address of the value in the process image and the value
itself, respectively.
If the value that should be written is only one bit wide, then the
.I i8uBit
field must be set as well, indicating which bit to write. In this case the
.I i8uValue
field can only contain the values
.BR 0 " or " 1 .

The address of a process image variable can be identified with a unique string
name by using the ioctl
.BR KB_FIND_VARIABLE (2).

The value can also be set through the
.BR piControl (4)
character device directly.
If only a single bit should be written, the
.BR ioctl (2)
should be used instead, as reading the byte first, modifying the bit, then
writing the byte again is done while holding a lock, which prevents a
race condition compared to 2 applications writing the same byte using the
.BR piControl (4)
character device.

.SH RETURN VALUE
On success, 0 is returned.

On error, \-1 is returned and
.I errno
is set to indicate the error.

.SH ERRORS
Error codes set in
.I errno
can be, among others, one of the following:
.TP
.B EAGAIN
A driver reset is in progress.
.TP
.B EINVAL
The
.I i16uAddress
field is set to a value that is bigger than the process image.
.TP
.B EFAULT
Failure on copying values to/from caller.

.SH SEE ALSO
.BR ioctl (2),
.BR KB_FIND_VARIABLE (2),
.BR KB_GET_VALUE (2),
.BR SPIValue (2type),
.BR piControl (4)
